version: '2'

services:
  elasticsearch:
    image: elasticsearch:6.3-alpine
    ports:
      - 9300:9300
      - 9200:9200
    command: -E network.host=0.0.0.0
    environment:
      - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
  postgres:
    image: postgres:9-alpine
    ports:
      - 5432:5432
